### ISSUE TITLE
Adding Motion as pod interferes with UIImagePickerController

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Motion#1]
Motion looks like an awesome library! Playing around with it now, and noticed something.

When adding the pod the delegates of `UIImagePickerControllerDelegate` is not called:
```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String: Any])
```
and
```
func imagePickerControllerDidCancel(_ picker: UIImagePickerController)
```
When removing Motion from the Podfile, the delegates work.

**Comment by daniel-jonathan** [comment]
Thank you! I think Motion will be a good one :) 

Can you send a sample so I can reproduce? I didn't use the UIImagePicker anywhere, but I could be overriding a delegation binding accidentally. Thank you!

**Comment by theolof** [comment]
OK, this was really weird.
If I do it like this:
`let imagePicker = UIImagePickerController()` in the class header
`imagePicker.delegate = self` in viewDidLoad()
it works fine **without** Motion in the Podfile, but **not with** Motion in the Podfile.

If I do it like this:
```
let imagePicker = UIImagePickerController()
imagePicker.delegate = self
```
in a local function just before I want to show the picker, it works **even** with Motion in the Podfile.

So, some weird stuff happened when I used Motion and had the declaration in the class header. No idea why, but it works fine with a local variable.

**Comment by theolof** [comment]
Too soon...it works as I described above when I start with a new project.

When I try the above in my real project, it still doesn't work with Motion in the Podfile...

No idea how you can reproduce this, since I cannot send you the whole project. I'll see if I can debug some more.

**Comment by daniel-jonathan** [comment]
I looked through Motion's code and think that this maybe the issue:

`Motion.swift`
```swift
extension UIViewController {
    open func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return isMotionEnabled ? Motion(isPresenting: true, isContainer: false) : nil
    }
    
    open func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return isMotionEnabled ? Motion() : nil
    }
    
    open func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
        return isMotionEnabled ? MotionPresentationController(presentedViewController: presented, presenting: presenting) : nil
    }
}
```

Can you try taking that out and see if the issue persists? You may get another issue, but I want to know if the UIImagePickerController works correctly. 

Thank you!

**Comment by theolof** [comment]
No, it didn't help.

However, this helps:
```
extension UINavigationController: UINavigationControllerDelegate {
    open override func viewDidLoad() {
        super.viewDidLoad()
        //delegate = self  <--- COMMENTED THIS LINE
    }
        @objc(navigationController:animationControllerForOperation:fromViewController:toViewController:)
    open func navigationController(_ navigationController: UINavigationController, animationControllerFor operation: UINavigationControllerOperation, from fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return fromVC.isMotionEnabled ? Motion(isPresenting: operation == .push, isContainer: true) : nil
    }
}
```

**Comment by daniel-jonathan** [comment]
Yes, the functions are only called when you set that value. I have an idea of how to fix it. I'll push an update to the `development` branch. I'll ping you when it is ready.

**Comment by daniel-jonathan** [comment]
I released [Motion 1.0.3](https://github.com/CosmicMind/Motion/releases/tag/1.0.3), which requires a manual setting for the `isMotionEnabled` property by the `UIImagePickerController`. Give it a try and let me know :) Thank you!

**Comment by theolof** [comment]
Yep, it works.

**Comment by daniel-jonathan** [comment]
Sweet :) Thanks for bringing this to my attention.
