### ISSUE TITLE
Transition Animations

### ISSUE THREAD

**Issue by Mahan3340** [CosmicMind/Motion#10]
Hi, I don't get how to use TransitionAnimations , in the example bellow the gifs I change my VC class to UINavigationController but cant find the variable motionTransitionType (or something like that ) , and in the examples codes you just used default swift UIViewController and cant find such these methods or Variables to set to .zoom or what .. , can you explain how to use these animations ??

**Comment by daniel-jonathan** [comment]
Have you had a chance to read through the documentation: https://www.gitbook.com/book/cosmicmind/motion/details ?

**Comment by Mahan3340** [comment]
yea i did dor sure but your example project has conflicts with your short code in documentation , in your exanole project u just used simple default uiviewcontroller and calling some prepare methods that include a variable that isnt found , in the doc u used navigationcontroller as class i did so bit still cant find a variable motiontype .. there ? so how should i use this ? use it az custom class ? please explain better for me

**Comment by daniel-jonathan** [comment]
How are you including `Motion` within your project?

**Comment by Mahan3340** [comment]
using pods , its installed successfuly , and i have to mention that the variable isMotionEnabled is foud ( dont know it's yours or swift default)

**Comment by daniel-jonathan** [comment]
In the sample I didn't import Motion because it is included in Material. You need to import Motion into your Swift files that use Motion's features. That should fix your issue :) if you need, please reopen or create a new issue.

**Comment by Mahan3340** [comment]
`
 import UIKit
import Material

class ConfirmVC: UIViewController {

      override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
    }
    override func viewDidLoad() {
        isMotionEnabled = true
         motionModalTransitionType = .autoReverse(presenting: .zoom)
        super.viewDidLoad()
    }.....`


motionModalTransitionType  this is not found , with importing Material , Motion , or both

**Comment by daniel-jonathan** [comment]
The first thing to notice is this is incorrect: 

```swift
override func viewDidLoad() {
    isMotionEnabled = true
     motionModalTransitionType = .autoReverse(presenting: .zoom)
    super.viewDidLoad()
}
```

You should have it like this:

```swift
override func viewDidLoad() {
super.viewDidLoad()
    isMotionEnabled = true
     motionModalTransitionType = .autoReverse(presenting: .zoom)
}
```

The second thing is that I am going to ask that you send over a sample project, because you should be able to use the Motion features. Can you send me a sample project that reproduces the issue?

**Comment by Mahan3340** [comment]
[Test.zip](https://github.com/CosmicMind/Motion/files/1185774/Test.zip)

this is test project created , I've added pods and installed them , and there are 2 VCs one name "fristVC" 
thats the one importing material and have the error 
(Thanks for the point you mentioned above)

**Comment by daniel-jonathan** [comment]
I tested your project and it looks like you are using Material 2.6.3. Make sure you clear your pod cache. 

<img width="571" alt="screen shot 2017-07-31 at 12 25 51 pm" src="https://user-images.githubusercontent.com/9982123/28792033-9d18d1b0-75eb-11e7-85cf-39c54978f04d.png">

Let me know how it works out :)
