### ISSUE TITLE
Add replay feature to animations.

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Motion#13]
This should allow for a number of iterations the animations are played.

**Comment by OrkhanAlikhanov** [comment]
Is this like [`CAAnimation.repeatCount`](https://developer.apple.com/documentation/quartzcore/camediatiming/1427666-repeatcount)?

**Comment by daniel-jonathan** [comment]
It would be like a loop, or repeat the animation `x` number of times.

**Comment by daniel-jonathan** [comment]
@adamdahan this would be a really cool feature.

**Comment by adamdahan** [comment]
@danieldahan Let's chat more context. !

**Comment by daniel-jonathan** [comment]
Definitely :) 

Basically the idea is to create a loop for animations that a developer may set. This is not of high priority, but would be a nice feature. We can plan it out accordingly, and actually, I think we should close this until the need actually comes up. So for now, keep it in mind.
