### ISSUE TITLE
Views alpha reseting to 1 after view disappear.

### ISSUE THREAD

**Issue by glm4** [CosmicMind/Motion#16]
Im using a TabBarController with fadeIn and fadeOut transition modes.
My issue is that some subviews of one of the presenting view controllers are setting the alpha back to 1 after I animated them with fadeOut before exiting the view controller.
It sounds like a problem with the fade transitions used between view controllers and views being animated as well.

Update: Problem persist after removing the subview fade animation. Seems to be completely related to the transition mode.

Using version 1.1.2 of cocoapods.

**Comment by daniel-jonathan** [comment]
This is a linked issue: https://github.com/CosmicMind/Material/issues/853

**Comment by daniel-jonathan** [comment]
I will be working on this either today or tomorrow :)

**Comment by glm4** [comment]
Very cool! Thanks a lot 😁

**Comment by daniel-jonathan** [comment]
Please give [Motion 1.3.0](https://github.com/CosmicMind/Motion/releases/tag/1.3.0) a try. If the issue persists, please reopen it. Thank you!
