### ISSUE TITLE
View blinks when popping view controller on UINavigationController

### ISSUE THREAD

**Issue by ghks1353** [CosmicMind/Motion#17]
First of all, sorry for my bad English.

I'm using `Motion` on my project in `UINavigationController`, view blinks with black color when pushing/pop view controller repeatedly after 10 times.

First 10 times of translation is OK and no glitches, but it blinks weirdly by repeating popping vieewcontroller a few times after.
Additional: And some subview blinks when pushing view controller after pushing 10 times.

I just enabled `isMotionEnabled` property on my `UINavController` and `UIViewController`.
Here is my view controller code for setup `Motion`:

`self.isMotionEnabled = true`
`self.navigationController?.motionNavigationTransitionType = .autoReverse(presenting: .fade)`
`current.motionIdentifier = "ppj-header-progress"`

I tried to remove `motionNavigationTransitionType` but same result.

Update: This issuse is caused on iPhone X, iOS 11.1.1
Update 2: My code works perfectly and not happening any issue on iPhone 4s, iOS 9 
Update 3: Not happening black blink issue on iPhone 5s, iOS 11 but some subviews translates weirdly (e.g. blinking layer shadows) when pushing/popping view.

![ezgif com-optimize](https://user-images.githubusercontent.com/6275109/32770116-c22626be-c961-11e7-89a4-b1e765a2f845.gif)

**Comment by daniel-jonathan** [comment]
Nice find. Can you send over the sample project you are using so I can easily reproduce this? As well, is this only happening in the simulator?

**Comment by ghks1353** [comment]
I attached sample project archive. You can see screen is blink weirdly after pushing viewcontrollers a few times after, also you can see blinking navigation bar on the top when pushing vc every time.
I added some views (like `UIImageView`) in my sample and it also blinking weirdly.

I tested on my real device of iPhone X, iPhone 4s and iPhone 5s, not simulator.
Simulator works fine and no glitches on my iPhone X simulator.

[sample.zip](https://github.com/CosmicMind/Motion/files/1473015/sample.zip)

**Comment by daniel-jonathan** [comment]
Thank you! I am going to test this today.

**Comment by daniel-jonathan** [comment]
Looking at this now. Thank you!

**Comment by daniel-jonathan** [comment]
Please give [Motion 1.3.0](https://github.com/CosmicMind/Motion/releases/tag/1.3.0) a try. If the issue persists, please reopen it. Thank you!
