### ISSUE TITLE
About extension CALayer: CAAnimationDelegate {}

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Motion#18]
I found the following code in Motion+CALayer.swift
@available(iOS 10, *)
extension CALayer: CAAnimationDelegate {}

The problem is now I want to make my own customize CALayer which conforms CAAnimationDelegate. But because of the "extension CALayer: CAAnimationDelegate {}", it seems I can not do it.

Can you help me to work it out? Thank you.

**Comment by daniel-jonathan** [comment]
Hey :) Yes, I can help. 

Have you tried only adding the CAAnimationDelegate protocol when necessary? Or could you not extend CALayer with the current CAAnimationDelegate added? What is the error you are getting?

**Comment by guoyingtao** [comment]
<img width="1188" alt="recordanimationlayer_swift" src="https://user-images.githubusercontent.com/26723384/32859214-d0e2c5ee-ca1b-11e7-801c-8ef6403f7974.png">
I attached the error screen shot.
RecordAnimationLayer is a subclass of CALayer

**Comment by guoyingtao** [comment]
Currently, I delegate CAAnimationDelegate to another object, that object then invoke functions from RecordAnimationLayer. It works for the time being. But I still hope to get a better solution. :)

**Comment by daniel-jonathan** [comment]
I'll take a look into this :)

**Comment by daniel-jonathan** [comment]
You should be able to subclass the extension independent of the extension I have added. If this is not possible, then let me know. Otherwise, there isn't much I can do.
