### ISSUE TITLE
Can I use different MotionTransitionType in one UIViewcontroller

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Motion#19]
Say I have a UIViewController UV1 which is embedded in an AppNavigationController and Another two UIViewController UV2 and UV3. I want to push UV2 or UV3 from UV1.

```
class AppNavigationController: NavigationController {
  open override func prepare() {
    super.prepare()
    isMotionEnabled = true
    motionNavigationTransitionType = .autoReverse(presenting: .zoom)
  }
}
```

The problem is both transitions for UV2 and UV3 is "zoom".
If I want the transition for UV2 is zoom, but the one for UV3 is "slide", what should I do to achieve it?
Thanks!

**Comment by daniel-jonathan** [comment]
You can adjust the different motion transition in each view controller. So in VC2 you can add in the viewDidLoad method: 

```swift
navigationController?.motionNavigationTransitionType = .autoReverse(presenting: .pageIn(direction: .down))
```

and so forth in the different view controllers. That is one way and a straight forward way to do so. If you need please reopen the issue for any further help on this topic. Thank you!

**Comment by guoyingtao** [comment]
It works. Thank you very much!

**Comment by daniel-jonathan** [comment]
Any time :)
