### ISSUE TITLE
Is there a way to know when the animation is complete?

### ISSUE THREAD

**Issue by ymkim50** [CosmicMind/Motion#2]
I am using the motion library very usefully.

However, I would like to have an event to know the end of motion.
We are currently using a function called delayedCall, but it would be nice to know this as an event.

Are you willing to support this?

Thank you for providing a good library.

**Comment by daniel-jonathan** [comment]
Hey, thank you :) Happy you like it. 

The functionality is already there. There are delegation calls you can tap into.  

```swift
@objc
func motion(motion: Motion, willTransition fromView: UIView, toView: UIView) {}
    
@objc
func motion(motion: Motion, didTransition fromView: UIView, toView: UIView) {}
```

The delegation calls are called in their corresponding view controller. For example, if you are transitioning from VC A to VC B. The `willTransition` delegate call is called in VC A, and the `didTransition` is called in VC B. 

That should do it :) Feel free to send more questions if you need help.

**Comment by ymkim50** [comment]
I'm sorry, my question is wrong.

I want to detect the completion of the animation in view.motion (...).

Is there a way to tell something like UIView.animate ()?

**Comment by daniel-jonathan** [comment]
Ah... you want a completion callback, and or animation callback?

**Comment by daniel-jonathan** [comment]
I made this a feature request. I will add this within the next couple days.

**Comment by m-revetria** [comment]
+1 This would be a helpful feature. I have a case where I want to remove a view after an animation, now I'm using `DispatchQueue.asyncAfter` with the animation's duration to achieve it

**Comment by ymkim50** [comment]
Thank you for your response.

My suggestion is that completion is more appropriate.

**Comment by daniel-jonathan** [comment]
Hey, I added this, will be out in the next release, which will be done latest tomorrow. I will notify you once ready. Thank you!

**Comment by ymkim50** [comment]
Thank you daniel.
I'll testing for next release and feedback any problem.

**Comment by daniel-jonathan** [comment]
Hey, in [Motion 1.0.4](https://github.com/CosmicMind/Motion/releases/tag/1.0.4) you will be able to add a completion handler for motion calls. For example: 

```swift
view.motion([.backgroundColor(.blue), .rotationAngle(45)]) {
    // Do something when complete.
}
```

Thank you and all the best!

**Comment by ymkim50** [comment]
Thank you. I'll test right now. good job.

**Comment by daniel-jonathan** [comment]
If you are using Material, I would wait 15 more minutes. I am launching Material 2.5, and that will have Motion built in for Material. Using both causes an issue with some extensions.

**Comment by daniel-jonathan** [comment]
Okay, you are good to try it out. I had to actually make an update. Thank you!

**Comment by ymkim50** [comment]
I applied the update to my project and tried the test. The animation test went well.

I have another question, but I will leave it as a different topic. We will also apply the material kit later.

I would like to say that I am very grateful for the addition.
