### ISSUE TITLE
Animation compile error of .delay

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Motion#20]
When I tried to code like following as the official documents said
animate([.rotate(270), .fadeOut, .scale(0.01), .delay(1)]){ [weak self] in
 }
Xcode gave me "Extra argument in call" compile error.
When I removed .delay(1), everything works fine again.

I also found I can not use .duration(1) like that neither.

**Comment by daniel-jonathan** [comment]
Make sure you are using a TimeInterval value. So you may need to specify that in your declaration or add ".0", so 1 is "1.0". Try that, if you have any further issues, please reopen this. Thank you!

**Comment by guoyingtao** [comment]
I tried to set 1 to 1.0 just like the following
myView.animate([.rotate(270), .fadeOut, .scale(0.01), .delay(1.0)]){ [weak self] in
}
It still didn't work.
When I removed .delay(1.0), it worked again.

**Comment by guoyingtao** [comment]
It seems I can not reopen the issues closed by you...

**Comment by daniel-jonathan** [comment]
Would you mind sending me a sample?
