### ISSUE TITLE
RightBarButtonItem is unclickable when using Xcode 9 + ios 10

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Motion#21]
When I use code as following, the rightBarButtonItem becomes unclickable (XCode 9 + ios 10),
But ios 11 is totally OK. When I changed back to normal UINavigationController, everything is OK again. Would you like to check this problem since there are many people who are still using ios 10.
Thanks a lot!

```
class AppNavigationController: NavigationController {
  open override func prepare() {
    super.prepare()
    isMotionEnabled = true
    motionNavigationTransitionType = .autoReverse(presenting: .zoom)
  }
}
```

**Comment by daniel-jonathan** [comment]
Can you try removing this line `isMotionEnabled = true`, it is set already upon creating the NavigationController. If that doesn't help, please send over a reproducible project. 

Thank you!

**Comment by daniel-jonathan** [comment]
Hey! I have not heard from you, so please reopen this issue if you need help. Thank you!
