### ISSUE TITLE
viewWillAppear etc. is not called MotionTransition

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Motion#24]
As of 1.3.2 `viewWillAppear(_:)`, `viewWillDisappear(_:)`, `viewDidAppear(_:)`, and `viewDidDisappear(_:)` are not invoked when we make transitions through `MotionTransition` since you removed calls to [`beginAppearanceTransition(_:animated:)`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621387-beginappearancetransition) and [`endAppearanceTransition()`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621503-endappearancetransition) in commit https://github.com/CosmicMind/Motion/commit/6b95e482892f73c52644c95d84c54a82587032bc

Material's `TabsController` is a victim of this change. I am not getting `viewWillAppear(_:)`-s anymore which my child view controllers heavily rely on

**Comment by daniel-jonathan** [comment]
I am going to make a fix for this today. Sorry about that. I was concerned about this happened.

**Comment by OrkhanAlikhanov** [comment]
No worries :) Thank you for your support!

**Comment by daniel-jonathan** [comment]
Please find a correct fix for this in [Material 2.13.3](https://github.com/CosmicMind/Material/releases/tag/2.13.3) and [Motion 1.3.3](https://github.com/CosmicMind/Motion/releases/tag/1.3.3).
