### ISSUE TITLE
Objective-C methods not available

### ISSUE THREAD

**Issue by ghost** [CosmicMind/Motion#25]
When trying to set an identifier in Obj-C the option to set the motionIdentifier does not exist. I have tried with setMotionIdentifier and with self.label.motionIdentifier.

Am I missing something?

**Comment by ghost** [comment]
**Issue Resolved:**

- In Objective-C you MUST use #import <Motion/Motion-Swift.h>
- Using @import's will not work

**Comment by daniel-jonathan** [comment]
@Xenero Thank you for sharing. I have added labels to help people find this solution more easily.
