### ISSUE TITLE
Minor typo in the description

### ISSUE THREAD

**Issue by 1tatarchuk** [CosmicMind/Motion#26]
I just found a minor typo - "Corder Radius" )

<img width="311" alt="screen shot 2018-02-06 at 3 51 50 pm" src="https://user-images.githubusercontent.com/32768181/35865777-b7d4a0ec-0b55-11e8-8f17-c2865b9ffb4c.png">

**Comment by daniel-jonathan** [comment]
Fixed and will be released in the next update. Thank you! Here is the commit d74082864a5df29e98eda1ddcdcec167aab5d805.
