### ISSUE TITLE
Animation error when using .rotate in transition struct

### ISSUE THREAD

**Issue by LiMinglun** [CosmicMind/Motion#28]
When uiview is rotated, half of the view disappears.

![img_0220](https://user-images.githubusercontent.com/31310711/36624921-fe7f31b6-1950-11e8-882d-ec85896f47d9.gif)

**Comment by daniel-jonathan** [comment]
Hey! I am not sure why I have not seen this issue. If you still face a problem or any other, please let me know. Thank you!
