### ISSUE TITLE
Jitter at animation end

### ISSUE THREAD

**Issue by apptekstudios** [CosmicMind/Motion#3]
I've just updated our code to utilise the new Motion framework instead of the old one built in to Material.

Using the Motion.rotation(angle:) function on a FabButton (as primary button of a Material Menu) works fine in terms of animating the button. However, we're noticing a flash of the initial animation state at the end of the rotation ([GIF recording](https://giphy.com/gifs/26xBKdH9hDedUwyU8))

`menu.views.first?.animate(animation: Motion.rotation(angle: -90))`

Any ideas what might cause this?

**Comment by daniel-jonathan** [comment]
Can you try using motion for this?

```swift
menu.views.first?.motion(.rotationAngle(-90))
```

**Comment by apptekstudios** [comment]
Thanks! That fixed the issue.

**Comment by daniel-jonathan** [comment]
Awesome :)
