### ISSUE TITLE
Can I create custom transition?

### ISSUE THREAD

**Issue by mlight3** [CosmicMind/Motion#30]
Can I create custom transition? Here is my interaction.
```
VC_1 (fromView)
 - topViewA
 - contentViewA
 - buttonA
 - bottomViewA

VC_2 (toView)
 - buttonB
 - topViewB
 - contentViewB
```

`bottomViewA` of VC_1 and `topViewB` of VC_2 is same view.
When VC_1 present VC_2, VC_1 and VC_2 is overwrapped with bottomViewA and then VC_1 is translated by y. It looks like scrolling effects.

So view layer looks like during transition
```
- topViewA
- contentViewA
- buttonA
- buttonB
- bottomViewA = topViewB
- contentViewB
```

Here is my code
```
toViewSnapshot.frame = CGRect(x: 0, y: bottomViewA.y, width: width, height: height)
fromViewSnapshot.addSubview(toViewSnapshot)

    UIView.animate(withDuration: 10, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseIn, animations: {
      snapshotFromView.frame = CGRect(x: 0, y: -bottomViewA.y, width: toView.frame.width, height: toView.frame.height)
    }, completion: { _ in
      self.snapshotViews.values.forEach { $0.removeFromSuperview() }
      self.snapshotViews.removeAll()
      transitionContext.completeTransition(true)
    })
```

If I added fromViewSnapshot and toViewSnapshot to containerView, I cannot create view hierarchy that I want (animating views are added toViewSnapshot or fromViewSnapshot)

After some search for a good solution, I found your project. This is awesome!
Could you give some advise if I use `Motion`?

**Comment by daniel-jonathan** [comment]
Hey! Yeah... have you had a chance to read the README? Basically it sounds like adding some motion identifiers would do most of the work if not all for you. When a view in VC_A has an identifier, and then transitions to VC_B, if a view with the same identifier exists there, then it will animate automatically for you, so long as the `isMotionEnabled` property is set to `true`. There is a lot more you can do, but that is the basic idea.
