### ISSUE TITLE
Swift 4.1 support (minor change)

### ISSUE THREAD

**Issue by Mahan3340** [CosmicMind/Motion#31]

**Comment by Tylerian** [comment]
@danieldahan Please consider this, my projects ain't building anymore without me editing the .pbxproj first each time I update carthage dependencies, I can make a pull request if you have no time to do it.

**Comment by daniel-jonathan** [comment]
Have you tried the latest release of Motion? I built with the latest Xcode using it. Let me know and I will be happy to make the change, as I am making some releases today. Thank you!

<img width="1209" alt="screen shot 2018-05-03 at 12 38 38 pm" src="https://user-images.githubusercontent.com/9982123/39596224-f0772a70-4ece-11e8-919c-5e21891a6e09.png">

If this is not correct, please reopen the issue. Thank you!
