### ISSUE TITLE
IMPORTANT SWIFT SETTINGS

### ISSUE THREAD

**Issue by ghost** [CosmicMind/Motion#33]
I was running into multiple errors like below:

`.../Pods/Material/Sources/iOS/Font.swift:97:59: Cannot force unwrap value of non-optional type 'CGFont' .../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:40:39: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:50:42: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/Material+NSMutableAttributedString.swift:61:42: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/Material+UIFont.swift:44:18: Type 'String' has no member 'font' .../Pods/Swift.String:231:16: Did you mean 'count'? .../Pods/Material/Sources/iOS/NavigationItem.swift:44:27: Cannot convert value of type 'Button' to specified type 'IconButton' .../Pods/Material/Sources/iOS/SearchBar.swift:112:83: Type 'String' has no member 'foregroundColor' .../Pods/Material/Sources/iOS/SearchBar.swift:122:83: Type 'String' has no member 'foregroundColor' .../Pods/Material/Sources/iOS/TextStorage.swift:108:93: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/TextStorage.swift:129:45: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/TextStorage.swift:141:45: Use of undeclared type 'NSAttributedStringKey' .../Pods/Material/Sources/iOS/TextStorage.swift:152:48: Use of undeclared type 'NSAttributedStringKey'`

The resolutions for this is to change the pods setting to use Swift 4.0. You can do this by selecting your Pods project in the project browser in XCode and then select the 'Material' pod/framework from the list of pods/frameworks on the left.

![image](https://user-images.githubusercontent.com/8923010/39664874-0569297c-507a-11e8-9f65-904bf4baf40f.png)

**Comment by daniel-jonathan** [comment]
Thank you for sharing this issue. Have you tried the latest release? What version are you currently running?

**Comment by daniel-jonathan** [comment]
I am closing this as I have not heard any response. Thank you!

**Comment by ghost** [comment]
Apologies. I missed your response. I am running the latest version.

**Comment by daniel-jonathan** [comment]
No worries. Please send over a sample project that demonstrates this issue.
