### ISSUE TITLE
Weak Should Not Be Applied In A Protocol

### ISSUE THREAD

**Issue by Gerst20051** [CosmicMind/Motion#34]
Pods/Motion/Sources/Preprocessors/MotionPreprocessor.swift:33:5

'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions

`weak var motion: MotionTransition! { get set }`

**Comment by daniel-jonathan** [comment]
Have you updated to the latest. This should have been all removed. 

<img width="473" alt="screen shot 2018-05-24 at 1 04 06 pm" src="https://user-images.githubusercontent.com/9982123/40500513-fb5b5b84-5f52-11e8-8587-cfd7547a3d9d.png">

**Comment by Gerst20051** [comment]
Thank you for pointing me in the right direction. The problem was because the pod `Material` is using version `~> 1.3.0` so Material needs to update to use the latest version. Thanks again! https://github.com/CocoaPods/Specs/blob/master/Specs/d/9/2/Material/2.15.0/Material.podspec.json#L40

**Comment by daniel-jonathan** [comment]
Ah, I will update the default. Thank you!
