### ISSUE TITLE
Shadow clipping when transitioning

### ISSUE THREAD

**Issue by TheSwiftyCoder** [CosmicMind/Motion#39]
Currently trying have a shadow on a UIView within a UITableViewCell and when performing the transition the cell shadow clips until the end animation state. I have all the normal properties set to false (clipsToBounds etc).  First approach was to attach the shadow to the UIView layer and that worked until Motion was introduced to the UITableView:

`	boxView?.layer.shadowColor = Theme.Colors.shadow!.cgColor
         boxView?.layer.shadowOpacity = 0.8
         boxView?.layer.shadowRadius = 20
         boxView?.layer.shadowOffset = CGSize(width: 0, height: 5)
         boxView?.layer.shadowPath = UIBezierPath(roundedRect: boxView.bounds, cornerRadius:20).cgPath`

Second approach is what I'm currently trying and that is to attach the shadow to the transition of the cell:

`			cell.boxView.isMotionEnabled = true
			cell.boxView.isMotionEnabledForSubviews = true
			cell.boxView.motionIdentifier = "box-\(indexPath.row)"
			cell.boxView.transition([
				.shadow(offset: CGSize(width: 0, height: 10)),
				.shadow(radius: 16),
				.shadow(color: Theme.Colors.green!),
				.shadow(opacity: 1),
				.shadow(path: UIBezierPath(roundedRect: cell.boxView.bounds, cornerRadius: 20).cgPath),
				.masksToBounds(false),
				.durationMatchLongest,
				.forceAnimate,
				.useGlobalCoordinateSpace,
				.useScaleBasedSizeChange
				])
			cell.layoutIfNeeded()`

Either approach fails to work and results in the cell shadow being clipped until the end of the animation motion provides.

The UITableView has the following MotionIdentifiers attached to it:

`basicTableView.transition([.beginWith(modifiers:[.zPosition(5)]), .useGlobalCoordinateSpace, .fade(0.0), .duration(0.25), .spring(stiffness: 300, damping: 25), .translate(x: -300), .masksToBounds(false)])`

Thanks

**Comment by daniel-jonathan** [comment]
Hey! Do you have a sample project we may try?

**Comment by daniel-jonathan** [comment]
Hey! I haven't heard from you. If this is still an issue, please reopen or create a new one. Thank you!
