### ISSUE TITLE
transparent background navigationcontroller

### ISSUE THREAD

**Issue by edon2005** [CosmicMind/Motion#41]
HI,

I have a strange problem. If I make transition by navigation controller from 1 to 2 view controller and 2nd viewcontroller has a transparent background so it get for some ms black. but it is possible to observe. Do you know how to solve it?

Thanks.

**Comment by daniel-jonathan** [comment]
I would be happy to help, please connect on [Material Gitter](https://gitter.im/CosmicMind/Material). Thank you!
