### ISSUE TITLE
What is this library's relationship to Hero?

### ISSUE THREAD

**Issue by jondwillis** [CosmicMind/Motion#46]
I notice that a lot of the APIs are the same, with some minor changes. Is this a fork of https://github.com/HeroTransitions/Hero ?

**Comment by daniel-jonathan** [comment]
Good question. 

Originally I wrote my own `Hero` type framework, and then `rewrote` a version from Hero and stuck with the `Hero` one as it was more robust. Now it has no relationship really.

**Comment by jondwillis** [comment]
Okay, cool. BTW, it made transitioning over a breeze! I wanted to use your one-off animation syntax as well as Hero-like features and using just the Motion library reduces the number of libraries I am using. Some of Hero's syntax has changed since the point you "forked" it, namely putting everything into a `.hero` extension on UIViews et al. for cleanliness.

For possible future people coming in from Google: I was doing some proxying when using Hero in a `UINavigationController` subclass where I needed to set the delegate, so I had to change some instances of `Hero.shared` into `MotionTransition.shared` and everything worked fine.

**Comment by daniel-jonathan** [comment]
@jondwillis Awesome! Please feel free to make any suggestions. Our aim is to continue expanding the framework.

**Comment by OrkhanAlikhanov** [comment]
@jondwillis Each file has mentioned original author of the code. By having a separate library `Motion`, we easily integrate and maintain it with `Material` framework. Also, Motion has some fixes that Hero lacks. `https://github.com/HeroTransitions/Hero/issues/222`
