### ISSUE TITLE
Support for custom timing functions

### ISSUE THREAD

**Issue by m-revetria** [CosmicMind/Motion#5]
Would be nice if we can use a custom timing function by passing the control points that define the animation curve.

**Comment by daniel-jonathan** [comment]
Yes, that is a feature I want to add very soon. I will leave this up as a feature request and prioritize it. Thank you!

**Comment by daniel-jonathan** [comment]
This is now available in the next release. Thank you!

**Comment by daniel-jonathan** [comment]
The fix for this issue is in [Motion 1.1.0](https://github.com/CosmicMind/Motion/releases/tag/1.1.0).
