### ISSUE TITLE
control interactive transition

### ISSUE THREAD

**Issue by pockerhead** [CosmicMind/Motion#52]
Hello! How can I control an interactive transition? In Hero we can do this like:

`

    @objc func pan(gr: UIPanGestureRecognizer) {

        let translation = gr.translation(in: self)

        switch gr.state {
        case .began:
            parentViewController?.dismiss(animated: true, completion: nil)
        case .changed:
            Hero.shared.update(translation.y / bounds.height)
        default:
            let velocity = gr.velocity(in: self)
            if ((translation.y + velocity.y) / bounds.height) > 0.5 {
                Hero.shared.finish()
            } else {
                Hero.shared.cancel()
            }
        }
    }
`

But in Motion we have the following lines, that commented:
`
/**
 ### The singleton class/object for controlling interactive transitions.
 
 ```swift
 Motion.shared
 ```
 
 #### Use the following methods for controlling the interactive transition:
 
 ```swift
 func update(progress: Double)
 func end()
 func cancel()
 func apply(transitions: [MotionTargetState], to view: UIView)
 ```
 */
`

May be there is another way to do this?

**Comment by OrkhanAlikhanov** [comment]
They are not commented out, it's just an informational comment. Actual code is in [`MotionTransition+Interactive.swift`](https://github.com/CosmicMind/Motion/blob/master/Sources/Transition/MotionTransition%2BInteractive.swift) file. But they are not marked as public. There are some bugs for interactive transition stuff right now. We are working on it and for next release it will be available.

**Comment by daniel-jonathan** [comment]
We will leave this open until the feature has been completed.

**Comment by OrkhanAlikhanov** [comment]
`development` branch now contains all the necessary code for interactive transitions.

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov thank you, and @pockerhead if you would like to join our `Slack` channel to give feedback and learn about how to use it best, send your email to `support@cosmicmind.com`.

**Comment by guidedways** [comment]
Just wondering if there's documentation on how to perform interactive transition on a UINavigationController using Motion?
