### ISSUE TITLE
Animate back to original state

### ISSUE THREAD

**Issue by andrealufino** [CosmicMind/Motion#58]
Hello. I'm using Motion to achieve a rotation effect on a button. This is what I'm doing : 
```
if isAdding {
    // Close adding, resetting all stuff
    btnAdd?.animate(MotionAnimation.rotate(45))
    isAdding = false
} else {
    // Open adding
    btnAdd?.animate(MotionAnimation.rotate(-45))
    isAdding = true
}
```

When I need to rotate back the button, I'm not able to achieve the "back" animation. How can I do? It seems the button starts always from the original position.

**Comment by OrkhanAlikhanov** [comment]
Hey! If you want to just revert the rotation to the original state just do:
```swift
button.animate(.rotate(0))
```

Or:
```swift
button.animate(.transform(CATransform3DIdentity))
```

`.rotation`, `.scale`, `.translate` all works through `view.layer.transform`. [Here is nice explanation](https://stackoverflow.com/q/34438889/)

**Comment by andrealufino** [comment]
Great! Thanks!
