### ISSUE TITLE
Application freeze when closing app while transition

### ISSUE THREAD

**Issue by mumensh** [CosmicMind/Motion#62]
Hi,

The issue is that if there is a motion transition happening and the user closed the app, the application stuck when open it again and can't do anything with it.

**Comment by daniel-jonathan** [comment]
@mumensh thank you for sharing this issue. What version of Motion are you using? As well, if you are using Material in conjunction... what version are you using there?

**Comment by OrkhanAlikhanov** [comment]
Hey @mumensh! I could not able to reproduce it. Can you provide a sample app reproducing it? Also as mention by @danieldahan please specify your Motion version.

**Comment by mumensh** [comment]
Hey @danieldahan & @OrkhanAlikhanov , thank you for your quick reply.

I've attached an example project for the bug, it's depending on cocoapods

I'm using the development branch and the version of Motion and Material is:
  - Material (3.0.0):
    - Material/Core (= 3.0.0)
  - Material/Core (3.0.0):
    - Motion (~> 2.0.0)
  - Motion (2.0.0):
    - Motion/Core (= 2.0.0)
  - Motion/Core (2.0.0)

I'm using Material and Motion in my app.

[motionBug.zip](https://github.com/CosmicMind/Motion/files/3004300/motionBug.zip)

The way to produce the bug is like the following:
1. Tap on the image in FirstViewController, this will open the SecondViewController
2. Drag the view in SecondViewController to the left, don't release your drag, then close the app.
3. If you open the app again, it will be stuck on the last transition location before closing the app.

Thank you.

**Comment by daniel-jonathan** [comment]
@mumensh Thank you, we will look into this as we prepare for pushing the `development` branch to `master` for release.

**Comment by OrkhanAlikhanov** [comment]
I couldn't play with your code too much but here is a problem that I see in your code: "You are not handling all ` UIGestureRecognizer.State`s. Especially 2 cases:
```swift
case cancelled
case failed
```
When those cases happen you need to call either `MotionTransition.shared.cancel()` or `MotionTransition.shared.finish()`.

I think `cancelled` state happens when the gesture is interrupted, like a phone call received or user hits home button during gesture. I have no idea when `failed` state is received, you can look it up in apple docs.

**Comment by mumensh** [comment]
@OrkhanAlikhanov You are right, I've implemented the `cancel` state, the issue gone, thank you.

**Comment by OrkhanAlikhanov** [comment]
Cool! We understand that we need to document the features and write guides so that developers don't lose their time on discovering features and using the framework in unintended ways. We are working towards that! Thank you!
