### ISSUE TITLE
The "Material - It's time to download" link is boken.

### ISSUE THREAD

**Issue by EmreSURK** [CosmicMind/Motion#67]
It gives 404 error.

**Comment by daniel-jonathan** [comment]
@EmreSURK Hey! Sorry about that. We are going through a big change with our documentation. Anything I can help you with in regards to obtaining Material? Or is this a helpful issue for us to know? Thank you! Also, you are asking about Material in Motion's repo. Is this about Motion or Material for you, or both?

**Comment by daniel-jonathan** [comment]
Take a look at this, and I am adding this to the README now. 

## CocoaPods

[CocoaPods](http://cocoapods.org) is a dependency manager for Cocoa projects. You can install it with the following command:

```bash
$ gem install cocoapods
```

To integrate Motion's core features into your Xcode project using CocoaPods, specify it in your `Podfile`:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Motion', '~> 3.1.0'
```

Then, run the following command:

```bash
$ pod install
```

## Carthage

Carthage is a decentralized dependency manager that builds your dependencies and provides you with binary frameworks.

You can install Carthage with Homebrew using the following command:

```bash
$ brew update
$ brew install carthage
```
To integrate Motion into your Xcode project using Carthage, specify it in your Cartfile:

```bash
github "CosmicMind/Motion"
```

Run `carthage update` to build the framework and drag the built `Motion.framework` into your Xcode project.
