### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by sejr** [CosmicMind/Motion#68]
I am excited to try this out after having used Hero in the past. I spent a few minutes reading the README looking for a quick snippet to add to my Podfile, but alas, none exists. I'd recommend adding it. :)

Thanks for the effort you have put into this!

**Comment by daniel-jonathan** [comment]
@sejr Thank you :) I am excited for you to try it too. We are working on an entirely new documentation portal, .... well actually our first documentation portal, and we are inches away from making it a reality. Sorry the README is lagging. For now, you should be able to use this:

I will add this to the README :)

## CocoaPods

[CocoaPods](http://cocoapods.org) is a dependency manager for Cocoa projects. You can install it with the following command:

```bash
$ gem install cocoapods
```

To integrate Motion's core features into your Xcode project using CocoaPods, specify it in your `Podfile`:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Motion', '~> 3.1.0'
```

Then, run the following command:

```bash
$ pod install
```

## Carthage

Carthage is a decentralized dependency manager that builds your dependencies and provides you with binary frameworks.

You can install Carthage with Homebrew using the following command:

```bash
$ brew update
$ brew install carthage
```
To integrate Motion into your Xcode project using Carthage, specify it in your Cartfile:

```bash
github "CosmicMind/Motion"
```

Run `carthage update` to build the framework and drag the built `Motion.framework` into your Xcode project.
