### ISSUE TITLE
Is there a provided way to animate depth?

### ISSUE THREAD

**Issue by AkitakiLab** [CosmicMind/Motion#7]
I use both Material and Motion in my project. I'm wondering if there's a way to animate depth change?
If not, would you add it in the future?

Thanks in advance

**Comment by daniel-jonathan** [comment]
I am combining Motion into Material for an enhanced Material feature set. I will try this out and let you know. I am doing this today, so I will get back to you shortly. There will still be a version of Motion that is standalone.

**Comment by daniel-jonathan** [comment]
I added this feature. It will be out in the next release :) Thank you!

**Comment by AkitakiLab** [comment]
Great! Thanks for your hard work on this!

**Comment by daniel-jonathan** [comment]
In [Motion 1.0.4](https://github.com/CosmicMind/Motion/releases/tag/1.0.4) you will be able to animate `depth` and its subparts (`shadowOffset`, `shadowOpacity`, `shadowRadius`). Thank you and all the best!
