### ISSUE TITLE
Having trouble animating ImageView of different contentMode and Size

### ISSUE THREAD

**Issue by gouen95** [CosmicMind/Motion#72]
Hi, I've a 1:1 square ratio of imageView with contentMode of scaleAspectFill and another screen to be transition into which contain another imageView (with the same identifier and image) with contentMode of scaleAspectFit and 9:16/1:2 ratio (iphone common ratio).

The whole transition of the 1:1 imageView is a stretch out and fade away..

Edit : scaleAspectFill is causing the stretching effect due to it's native behaviour. When the transition trying to change/adust the size of the imageView to the 2nd imageView, the image inside reacts to the change of size too.

Any help would be appreciated. Thanks.

**Comment by adamdahan** [comment]
@gouen95 Can you provide me with a small sample project? happy to take a crack at a fix for you :)

**Comment by adamdahan** [comment]
@gouen95 Feel free to open this ticket again with some sample code 👍
