### ISSUE TITLE
Transition always uses zoom effect

### ISSUE THREAD

**Issue by tigloo** [CosmicMind/Motion#75]
I'm trying to create a similar onboarding workflow as PaperOnboarding but want to use Motion for the animation and transition work. When transitioning from one onboarding page to the next, Motion always applies the zoom effect and I don't seem to be able to override that.

I've added a sample project to illustrate the issue I'm having.

The structure is as following:
- OnboardingViewController: container view controller, contains an instance of CardboardOnboarding
- CardboardOnboarding: this is where the onboarding pages are set up and where animation is configured
- CardboardOnboardingPage: a single page of the onboarding workflow (does nothing really except for holding all the widgets)

The transitions are done manually in CardboardOnboarding.present().

Expectation: the page image and page text should cross fade, the page indicators at the bottom should translate to the new position.

Observed effect: at least the page image and the page indicators go through some kind of zoom effect, overlaid with a fade.

I'm not sure how to get rid of the zoom and would appreciate any help.
[motionDebug.zip](https://github.com/CosmicMind/Motion/files/3616021/motionDebug.zip)

**Comment by daniel-jonathan** [comment]
Hi @tigloo, I will investigate the reason *zoom* is always on. Check-in with me in a couple days if you don't hear from me. Thank you!

**Comment by tigloo** [comment]
Hi @danieldahan, just pinging to get your attention. Thanks for taking a look!

The effect can also be seen at the page indicators at the bottom which translate and zoom at the same time.

**Comment by daniel-jonathan** [comment]
Hi @tigloo looking at this today. Sorry for any delays.

**Comment by sungwoochang** [comment]
having same issue

**Comment by tigloo** [comment]
@danieldahan, do you have any updates on this issue? Were you able to reproduce it?

**Comment by daniel-jonathan** [comment]
Sorry, we haven't had a chance to look into this issue. We will shortly. Thank you!

**Comment by tigloo** [comment]
Any updates on this? Thanks!

**Comment by tigloo** [comment]
@danieldahan It's been about two months - is there anything you can do?

Would also be grateful for any pointers to debug and patch this myself. I stepped through the code but I'm not quite clear on where effects are assigned and retrieved. If you can share any thoughts on where you think it goes wrong, that would also help.

**Comment by OrkhanAlikhanov** [comment]
Hey! Sorry. I checked the sample app you provided, and it took some time for me to clean it up and see the real issue. Please, always try to provide [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)

Removing following `translatesAutoresizingMaskIntoConstraints` lines fixes the zoom issue: 
```swift
newPage.view.translatesAutoresizingMaskIntoConstraints = false 
newPage.pageIndicators.translatesAutoresizingMaskIntoConstraints = false
```
Motion takes size of the image view with identifier `pageImage` from the `fromViewController`, and tries to interpolate it to the size of a view with same identifier in the `toViewController`. The problem is that size of imageview in `toViewController` becomes large somehow (I think due to layout issues) just before Motion takes note of its size. Hence resulting in zoom-like animation.

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov  thank you very much for looking into this. Awesome work!

**Comment by tigloo** [comment]
Thanks a lot for your help, @OrkhanAlikhanov! Sorry for not being more minimal on the example, I was unable to reproduce it in a smaller sample and couldn't pin point it in what I provided.

I'm not seeing the cross-fade in the image yet but the other widgets work as expected - so should be able to work from here. Thanks!

**Comment by OrkhanAlikhanov** [comment]
I apologize if I sounded harsh, reading my comment now and it sounded a bit harsh to me lol. Glad that it helped!
