### ISSUE TITLE
Properties conflict with Apple's CoreMotion

### ISSUE THREAD

**Issue by ngbaanh** [CosmicMind/Motion#9]
Some properties seem conflict with CoreMotion such as `isMotionEnabled`, `motionIdentifier`.
It shows 
```
Ambiguous use of 'isMotionEnabled'
Ambiguous use of 'motionIdentifier'
Ambiguous reference to member 'animate'
```
The problem happened on Xcode8.3, Swift3.
<img width="652" alt="screen shot 2017-07-25 at 2 32 20 pm" src="https://user-images.githubusercontent.com/14954130/28560777-1c1b8c3c-7146-11e7-8a33-f29fd5a5cd51.png">

**Comment by daniel-jonathan** [comment]
Hey :) you shouldn't import the Motion framework with Material, as Material already imports it for you. Reopen the issue if you still have any problems. All the best.

**Comment by ngbaanh** [comment]
@danieldahan Yes I tried as you said, but still not work (then I tried as the image shown above). 
ps: I got this from Animation Sample Code.
<img width="1387" alt="screen shot 2017-07-25 at 4 14 46 pm" src="https://user-images.githubusercontent.com/14954130/28564842-83cdb658-7154-11e7-9cbd-65204ec05e03.png">

**Comment by daniel-jonathan** [comment]
Make sure to include Material as an embedded framework: 

<img width="1680" alt="screen shot 2017-07-25 at 6 33 31 am" src="https://user-images.githubusercontent.com/9982123/28568452-d2ed9812-7103-11e7-8af9-adc425e0dcb2.png">

I just ran the sample Animations project and all worked correctly.

Possibly, you may need to set `.delay(1)`, to `.delay(1.0)`, as it is a TimeInterval. 

Let me know how it works out. Thank you!

**Comment by ngbaanh** [comment]
Yeah, It worked following your way (manually add Material framework into the project), but for cocoapods it didn't work. Maybe the Material version of cocoapods was outdated (`2.6.3`) while the new way its version is `2.7.0`.
When I change `pod 'Material', '~> 2.0'` by default to `pod 'Material', '2.7.0'`, it works like a charm.

The issue should be ended. Thank you for your support.

**Comment by daniel-jonathan** [comment]
Awesome! Also, sometimes when you update, you need to clear the CocoaPods cache. All the best!
